services:
  app:
    build: .
    container_name: schooltechshare
    ports:
      - 3001:3001
    volumes:
      # Persist the SQLite database
      - ./database.sqlite:/usr/src/app/database.sqlite
      # Persist uploaded images
      - ./public/uploads:/usr/src/app/public/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ADMIN_EMAIL=admin@schooltechshare.local
      - ADMIN_PASSWORD=Blumenstrasse4
    restart: always
